# Generated by Django 2.2.4 on 2019-08-05 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='blog'),
        ),
    ]
