# Generated by Django 2.2.4 on 2019-08-05 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_articulo_cover'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articulo',
            options={'ordering': ['-created'], 'verbose_name': 'Articulo', 'verbose_name_plural': 'Articulos'},
        ),
        migrations.AlterModelOptions(
            name='autor',
            options={'verbose_name': 'Autor', 'verbose_name_plural': 'Autor'},
        ),
    ]
