# Generated by Django 2.2.4 on 2019-08-05 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190805_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='nombre',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='autor',
            name='bio',
            field=models.TextField(blank=True, max_length=700),
        ),
    ]
