# Generated by Django 2.2.4 on 2019-08-05 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190805_1513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autor',
            name='nombre',
        ),
    ]
