# Generated by Django 2.2.4 on 2019-08-05 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20190805_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
